; SnappyMail Domain Config File
; https://github.com/the-djmaze/snappymail/blob/master/snappymail/v/0.0.0/app/Domains/default.ini

[domain]
imap_host = mailserver
imap_port = 993
imap_secure = SSL

smtp_host = mailserver
smtp_port = 465
smtp_secure = SSL

sieve_host =
sieve_port = 4190
sieve_secure =

use_local_sieve = false

white_list =
